[project]
name = "student"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Karamthot Anil Naik", email = "kanilnaik2005@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.57.0",
    "tensorflow>=2.21.0",
    "torch>=2.14.0",
]

[project.scripts]
student = "student:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
